language: scala

before_script:
  - openssl aes-256-cbc -K $encrypted_12c8071d2874_key -iv $encrypted_12c8071d2874_iv -in secrets.zip.enc -out secrets.zip -d
  - git remote add ssh-origin "git@github.com:wellcometrust/scala-monitoring.git"

cache:
  directories:
    - $HOME/.sbt
    - $HOME/.ivy2/cache
    - project/target
    - monitoring/target
    - monitoring_typesafe/target


# Everything below this line is boilerplate that should be reusable,
# unmodified, in any of our Scala library repos.

sudo: false

scala:
- 2.12.6

branches:
  only:
    - master

env:
  global:
    # This forces Python to print everything to stdout/stderr immediately.
    - PYTHONUNBUFFERED=x

jobs:
  include:
    - stage: format
      env: TASK=format
    - stage: test
      env: TASK=test
    - stage: release
      env: TASK=release

script:
  - ./sbt_release_tooling.py "$TASK"

stages:
  - format
  - test
  - name: release
    if: type = push
